import type { Metadata } from "next";
import "../globals.css";
import { Header } from "@/components/shared/header";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function HomeLayout({
    children,
    modal
}: Readonly<{
    children: React.ReactNode;
    modal: React.ReactNode;
}>) {
    return (
        <>
            <Header />
            <main>{children}</main>
            {modal}
        </>
    );
}
